Fix tables and force same style
xmos/lib_xcore_math pull request #153
Opened 2023-09-27 10:25 UTC by lucianomartin

I fixed in this PR the problems described in https://xmosjira.atlassian.net/browse/AP-152.

I have also forced all the table to use the 'longtable' style, i.e. they have borders. I had to do that because I can't force a long table, i.e. one table with more than 30 rows, to use the normal style without border.

The generated pdf doc is attached.

[programming_guide.pdf](https://github.com/xmos/lib_xcore_math/files/12737490/programming_guide.pdf)

Closes https://xmosjira.atlassian.net/browse/AP-162

2023-09-27 12:42 UTC, mbanth requested changes
The table re-formatting all looks good in PDF.  Is it generated in HTML as well?  If so, can you please provide a link so I can take a look?

I have noted two small issues with the content on the tables which I would like corrected as part of this PR.

2023-09-27 13:25 UTC, lucianomartin commented on doc/programming_guide/src/reference/scalar/scalar_quickref.rst
>      :file: csv/scalar_complex_float_ops.csv
all the csv tables have a blank line at the bottom. This is probably done to avoid the red sign for  "No newline at end of file" on github.

2023-09-27 13:44 UTC, lucianomartin commented on doc/programming_guide/src/reference/scalar/scalar_quickref.rst
>      :file: csv/scalar_complex_float_ops.csv
Sorry, my reply above is wrong. Now I see the problem, I removed the extra blank line.

2023-09-27 14:02 UTC, lucianomartin commented on doc/programming_guide/src/reference/bfp/bfp_quickref.rst
>  .. csv-table:: 32-Bit BFP API - Quick Reference
I fixed all the issue in this comment apart from the left-justify. The table is already left-aligned and we don't have control over the word spacing. I could try to play with the column width to have a better spacing, but I won't be able to find a good value satisfying all the rows.

2023-09-27 16:04 UTC, mbanth approved these changes
Looks good.

2023-09-27 16:05 UTC, uvvpavel approved these changes
Reviewed both html and pdf. Both look good!

2023-09-28 07:26 UTC, merged

2023-09-28 07:35 UTC, lucianomartin commented
> The table re-formatting all looks good in PDF. Is it generated in HTML as well? If so, can you please provide a link so I can take a look?
> 
> I have noted two small issues with the content on the tables which I would like corrected as part of this PR.

@mbanth, sorry I missed your first request. The html files from the latest version is attached here. Usually the tables in html format correctly, but it is good to check. Pavel had a look already.
[html.zip](https://github.com/xmos/lib_xcore_math/files/12746883/html.zip)